export default function PricingBackground() {
  return (
    <svg viewBox="0 0 2880 1943" fill="none" xmlns="http://www.w3.org/2000/svg">
      <g opacity="0.07" clip-path="url(#clip0_13_195)">
        <rect x="-129" y="-52" width="3138" height="1384" fill="black" />
        <rect
          x="480"
          y="160"
          width="160"
          height="160"
          fill="#E3E3E3"
          className="animate-pulse"
        />
        <rect
          x="320"
          y="800"
          width="160"
          height="160"
          fill="#E3E3E3"
          className="animate-pulse"
          style={{ animationDelay: "0.1s" }}
        />
        <rect
          x="800"
          y="640"
          width="160"
          height="160"
          fill="#E3E3E3"
          className="animate-pulse"
          style={{ animationDelay: "0.2s" }}
        />
        <rect
          x="1120"
          y="480"
          width="160"
          height="160"
          fill="#E3E3E3"
          className="animate-pulse"
          style={{ animationDelay: "0.3s" }}
        />
        <rect
          x="1440"
          y="640"
          width="160"
          height="160"
          fill="#E3E3E3"
          className="animate-pulse"
          style={{ animationDelay: "0.4s" }}
        />
        <rect
          x="1760"
          y="960"
          width="160"
          height="160"
          fill="#E3E3E3"
          className="animate-pulse"
          style={{ animationDelay: "0.5s" }}
        />
        <rect
          x="2400"
          y="960"
          width="160"
          height="160"
          fill="#E3E3E3"
          className="animate-pulse"
          style={{ animationDelay: "0.6s" }}
        />
        <rect
          x="2080"
          y="320"
          width="160"
          height="160"
          fill="#E3E3E3"
          className="animate-pulse"
          style={{ animationDelay: "0.7s" }}
        />
        <rect
          x="1600"
          y="160"
          width="160"
          height="160"
          fill="#E3E3E3"
          className="animate-pulse"
          style={{ animationDelay: "0.8s" }}
        />
        <rect
          x="1"
          y="1"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="161"
          y="1"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="321"
          y="1"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="481"
          y="1"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="641"
          y="1"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="801"
          y="1"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="961"
          y="1"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1121"
          y="1"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1281"
          y="1"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1441"
          y="1"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1601"
          y="1"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1761"
          y="1"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1921"
          y="1"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2081"
          y="1"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2241"
          y="1"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2401"
          y="1"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2561"
          y="1"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2721"
          y="1"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1"
          y="161"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="161"
          y="161"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="321"
          y="161"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="481"
          y="161"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="641"
          y="161"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="801"
          y="161"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="961"
          y="161"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1121"
          y="161"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1281"
          y="161"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1441"
          y="161"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1601"
          y="161"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1761"
          y="161"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1921"
          y="161"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2081"
          y="161"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2241"
          y="161"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2401"
          y="161"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2561"
          y="161"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2721"
          y="161"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1"
          y="321"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="161"
          y="321"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="321"
          y="321"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="481"
          y="321"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="641"
          y="321"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="801"
          y="321"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="961"
          y="321"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1121"
          y="321"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1281"
          y="321"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1441"
          y="321"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1601"
          y="321"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1761"
          y="321"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1921"
          y="321"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2081"
          y="321"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2241"
          y="321"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2401"
          y="321"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2561"
          y="321"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2721"
          y="321"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1"
          y="481"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="161"
          y="481"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="321"
          y="481"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="481"
          y="481"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="641"
          y="481"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="801"
          y="481"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="961"
          y="481"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1121"
          y="481"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1281"
          y="481"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1441"
          y="481"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1601"
          y="481"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1761"
          y="481"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1921"
          y="481"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2081"
          y="481"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2241"
          y="481"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2401"
          y="481"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2561"
          y="481"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2721"
          y="481"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1"
          y="641"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="161"
          y="641"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="321"
          y="641"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="481"
          y="641"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="641"
          y="641"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="801"
          y="641"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="961"
          y="641"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1121"
          y="641"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1281"
          y="641"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1441"
          y="641"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1601"
          y="641"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1761"
          y="641"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1921"
          y="641"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2081"
          y="641"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2241"
          y="641"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2401"
          y="641"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2561"
          y="641"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2721"
          y="641"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1"
          y="801"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="161"
          y="801"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="321"
          y="801"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="481"
          y="801"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="641"
          y="801"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="801"
          y="801"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="961"
          y="801"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1121"
          y="801"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1281"
          y="801"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1441"
          y="801"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1601"
          y="801"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1761"
          y="801"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1921"
          y="801"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2081"
          y="801"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2241"
          y="801"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2401"
          y="801"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2561"
          y="801"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2721"
          y="801"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1"
          y="961"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="161"
          y="961"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="321"
          y="961"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="481"
          y="961"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="641"
          y="961"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="801"
          y="961"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="961"
          y="961"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1121"
          y="961"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1281"
          y="961"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1441"
          y="961"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1601"
          y="961"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1761"
          y="961"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1921"
          y="961"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2081"
          y="961"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2241"
          y="961"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2401"
          y="961"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2561"
          y="961"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2721"
          y="961"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1"
          y="1121"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="161"
          y="1121"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="321"
          y="1121"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="481"
          y="1121"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="641"
          y="1121"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="801"
          y="1121"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="961"
          y="1121"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1121"
          y="1121"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1281"
          y="1121"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1441"
          y="1121"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1601"
          y="1121"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1761"
          y="1121"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="1921"
          y="1121"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2081"
          y="1121"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2241"
          y="1121"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2401"
          y="1121"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2561"
          y="1121"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <rect
          x="2721"
          y="1121"
          width="158"
          height="158"
          stroke="white"
          strokeOpacity="0.75"
          strokeWidth="2"
        />
        <g filter="url(#filter0_f_13_195)">
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M1440 5H0V640V1275H1440H2880V640V5H1440ZM1440 5C2235.29 5 2880 289.299 2880 640C2880 990.701 2235.29 1275 1440 1275C644.71 1275 0 990.701 0 640C0 289.299 644.71 5 1440 5Z"
            fill="black"
          />
        </g>
      </g>
      <ellipse
        cx="1440"
        cy="1280"
        rx="957"
        ry="663"
        fill="url(#paint0_radial_13_195)"
      />
      <defs>
        <filter
          id="filter0_f_13_195"
          x="-150"
          y="-145"
          width="3180"
          height="1570"
          filterUnits="userSpaceOnUse"
          colorInterpolationFilters="sRGB"
        >
          <feFlood flood-opacity="0" result="BackgroundImageFix" />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feGaussianBlur
            stdDeviation="75"
            result="effect1_foregroundBlur_13_195"
          />
        </filter>
        <radialGradient
          id="paint0_radial_13_195"
          cx="0"
          cy="0"
          r="1"
          gradientUnits="userSpaceOnUse"
          gradientTransform="translate(1440 1280) rotate(90) scale(663 957)"
        >
          <stop stopColor="#fde047" stopOpacity="0.4" />
          <stop offset="0.6" stopColor="#fde047" stopOpacity="0.1" />
          <stop offset="1" stopColor="#fde047" stopOpacity="0" />
        </radialGradient>
        <clipPath id="clip0_13_195">
          <rect width="2880" height="1280" fill="white" />
        </clipPath>
      </defs>
    </svg>
  )
}
